# Generated by Django 5.2.13 on 2026-04-26 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PERSON", "Person"),
                            ("GROUP", "Group"),
                            ("PLACE", "Place"),
                            ("ORGANIZATION", "Organization"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("wikipedia_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("when_year", models.PositiveSmallIntegerField()),
                ("when_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("when_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "when_end_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "when_end_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "when_end_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("when_text", models.CharField(max_length=120)),
                ("why", models.TextField(blank=True)),
                (
                    "significance",
                    models.CharField(
                        choices=[
                            ("MAJOR", "Major"),
                            ("NORMAL", "Normal"),
                            ("MINOR", "Minor"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("WIKIPEDIA", "Wikipedia"),
                            ("WEB", "Web"),
                            ("BOOK", "Book"),
                            ("NOTE", "Note"),
                            ("OTHER", "Other"),
                        ],
                        default="WIKIPEDIA",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("source_citation", models.CharField(blank=True, max_length=300)),
                ("source_snippet", models.TextField()),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_here",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["when_year", "when_month", "when_day"],
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.entity"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.event"
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "entity")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                related_name="events", through="core.EventParticipant", to="core.entity"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("title", "when_year"), name="event_title_year_unique"
            ),
        ),
    ]
